version: 6.0.0-pre{build}
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))deploy:
branches:
  only:
  - master
build_script:
- ps: ./build.ps1
test: off
artifacts:
- path: artifacts/packages/*.nupkg
- provider: NuGet
  server: https://www.myget.org/F/ahoy/
  api_key:
    secure: 43SK7fLJcrno252Wqb6j+jFYeTjaHG8EWXruhHv6kW+bbySa4uBGTPNFjA7lzD0Y
  skip_symbols: true
  on:
    branch: master


