version: 6.0.0-pre{build}
branches:
  only:
  - master
build_script:
- ps: >-
    Import-Module .\tools\psake\psake.psm1
    Invoke-psake .\build-definition.ps1 dotnet-restore
    Invoke-psake .\build-definition.ps1 dotnet-build
    Invoke-psake .\build-definition.ps1 dotnet-pack
test: off
artifacts:
- path: artifacts/packages/*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/ahoy/
  api_key:
    secure: 43SK7fLJcrno252Wqb6j+jFYeTjaHG8EWXruhHv6kW+bbySa4uBGTPNFjA7lzD0Y
  skip_symbols: true
  on:
    branch: master


